export const COUNTRIES_MAP: Record<string, string> = {
  Andorian: 'Andorra',
  Emirian: 'United Arab Emirates',
  Afghani: 'Afghanistan',
  Anguillan: 'Anguilla',
  Armenian: 'Armenia',
  Angolian: 'Angola',
  Antarctic: 'Antarctica',
  Argentine: 'Argentina',
  Austrian: 'Austria',
  Australian: 'Australia',
  Arubian: 'Aruba',
  Bangladeshi: 'Bangladesh',
  Barbadian: 'Barbados',
  Belgian: 'Belgium',
  Bahrainian: 'Bahrain',
  Bermuda: 'Bermuda',
  Bolivian: 'Bolivia',
  Brazilian: 'Brazil',
  Bahameese: 'Bahamas',
  Bhutanese: 'Bhutan',
  Bulgarian: 'Bulgaria',
  Belarusian: 'Belarus',
  Belizean: 'Belize',
  Canadian: 'Canada',
  Congolese: 'Congo',
  Chinese: 'China',
  Swiss: 'Switzerland',
  Chilean: 'Chile',
  Cambodian: 'Cambodia',
  Cameroonian: 'Cameroon',
  Columbian: 'Columbia',
  Czech: 'Czech Republic',
  'Costa Rican': 'Costa Rica',
  Cuban: 'Cuba',
  Cypriot: 'Cyprus',
  German: 'Germany',
  Danish: 'Denmark',
  Dominican: 'Dominica',
  Ecuadorean: 'Ecuador',
  Estonian: 'Estonia',
  Egyptian: 'Egypt',
  Ethiopian: 'Ethiopia',
  Finnish: 'Finland',
  Fijian: 'Fiji',
  French: 'France',
  British: 'United Kingdom',
  Georgian: 'Georgia',
  Ghanaian: 'Ghana',
  Guinean: 'Guinea',
  Greek: 'Greece',
  Guyanese: 'Guyana',
  Croatian: 'Croatia',
  Hungarian: 'Hungary',
  Indonesian: 'Indonesia',
  Irish: 'Ireland',
  Indian: 'India',
  Iraqi: 'Iraq',
  Iranian: 'Iran',
  Israeli: 'Israel',
  Icelander: 'Iceland',
  Italian: 'Italy',
  Jamaican: 'Jamaica',
  Jordanian: 'Jordan',
  Japanese: 'Japan',
  Kenyan: 'Kenya',
  Korean: 'Korea',
  Kuwaiti: 'Kuwait',
  Kazakhstani: 'Kazakhstan',
  Lebanese: 'Lebanon',
  'Sri Lankan': 'Sri Lanka',
  Lithuanian: 'Lithuania',
  Luxembourger: 'Luxembourg',
  Moroccan: 'Morocco',
  Monacan: 'Monaco',
  Mexican: 'Mexico',
  Mayanmarese: 'Myanmar',
  Mongolian: 'Mongolia',
  Macau: 'Macau',
  Mauritian: 'Mauritius',
  Maldivan: 'Maldives',
  Malaysian: 'Malaysia',
  Namibian: 'Namibia',
  Nigerian: 'Nigeria',
  Dutch: 'Netherland',
  Norwegian: 'Norway',
  Nepalese: 'Nepal',
  'New Zealander': 'New Zealand',
  Omani: 'Oman',
  Panamanian: 'Panama',
  Peruvian: 'Peru',
  Filipino: 'Philippines',
  Pakistani: 'Pakistan',
  Polish: 'Poland',
  Portugees: 'Portugal',
  Paraguayan: 'Paraguay',
  Qatari: 'Qatar',
  Romanian: 'Romania',
  Russian: 'Russia',
  'Saudi Arabian': 'Saudi Arabia',
  Seychellois: 'Seychelles',
  Swedish: 'Sweden',
  Singaporean: 'Singapore',
  Slovakian: 'Slovakia',
  Senegalese: 'Senegal',
  Somali: 'Somalia',
  Spanish: 'Spain',
  Thai: 'Thailand',
  Tunisian: 'Tunisia',
  Turkish: 'Turkey',
  Taiwanese: 'Taiwan',
  Tanzanian: 'Tanzania',
  Ukrainian: 'Ukraine',
  Ugandan: 'Uganda',
  American: 'United States of America',
  Uruguayan: 'Uruguay',
  Uzbekistani: 'Uzbekistan',
  Venezuelan: 'Venezuela',
  Vietnamese: 'Vietnam',
  Yemeni: 'Yemen',
  'South African': 'South Africa',
  Zambian: 'Zambia',
  Zimbabwean: 'Zimbabwe',
}

export type Countries = keyof typeof COUNTRIES_MAP
